FROM mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
# Install the xz-utils package
RUN apt-get update && apt-get install -y mariadb-client virtualenv python3-venv
RUN echo ">>>> Custom Dev Container"