version: '3.8'
services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached      
    network_mode: service:maria_db
    command: sleep infinity

  pg_db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  
  maria_db:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MARIADB_USER: appusr
      MARIADB_PASSWORD: apppwd
      MARIADB_DATABASE: appdb
      MARIADB_ROOT_PASSWORD: approotpwd

volumes:
  postgres-data:
  mariadb-data: